name: 'Pull Request Benchmark'
author: ''
description: 'Continuous benchmark of pull requests to monitor performance regression'
branding:
  icon: 'fast-forward'
  color: 'blue'

inputs:
  name:
    description: 'Name of the benchmark. This value must be identical among all benchmarks'
    required: true
    default: 'Benchmark'
  tool:
    description: 'Tool to use get benchmark output. One of "cargo", "go", "benchmarkjs", "pytest"'
    required: true
  pr-benchmark-file-path:
    description: 'A path to file which contains the benchmark output from the pull request'
    required: true
  base-benchmark-file-path:
    description: 'A path to file which contains the benchmark output from the base branch of the pull request'
    required: true
  github-token:
    description: 'GitHub API token to post commit comments when `comment-always` or `comment-on-alert` are set'
    required: false
  comment-always:
    description: 'Leave a comment with the benchmark result comparison. To enable this feature, the `github-token` input is required'
    required: false
    default: false
  comment-on-alert:
    description: 'Leave a comment when the PR benchmark result is worse than the base branch, based on the threshold specified in the `alert-comment-threshold` input. To enable this feature, the `github-token` input is required'
    required: false
    default: false
  alert-threshold:
    description: 'Threshold which determines when to trigger a comment alert. Percentage values such as "150%" are supported. For example, 150% means that an alert happens when the PR benchmark result is 1.5x slower than the base branch'
    required: false
    default: '200%'
  fail-on-alert:
    description: 'Workflow fails when `fail-treshold` is exceeded'
    required: false
    default: true
  fail-threshold:
    description: 'Threshold which determines when the workflow should fail. Format is the same as the `alert-threshold` input. If this value is not specified, the same value as `alert-threshold` is used'
    required: false
  alert-comment-cc-users:
    description: 'Github users that will be mentioned in commit comment on alerts. The usernames need to be prefixed by @, and multiple users need to be comma-separated (e.g. "@foo,@bar"). '
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
